apiVersion: v1
kind: Secret
metadata:
  name: risk-api-secrets
  namespace: enterprise-risk
type: Opaque
stringData:
  API_KEY: replace-me
  DATABASE_URL: postgresql+psycopg2://risk_user:replace-me@postgres:5432/riskdb
  MLFLOW_DATABASE_URL: postgresql://risk_user:replace-me@postgres:5432/riskdb
  POSTGRES_PASSWORD: replace-me
